travis:
  secure:
    BINSTAR_TOKEN: foq/+9kU2E+wW/K22RfyHXpCVfsoMnEvx/W3DJghjlBwcoyqh0P39MjLnHOOEexgJdBePYnTTqC72ic1p/3o3iAw/zf1Fu65TaTe922dtiU30Iknnuy1i3XF/60cqANcabNTVx6TtMw/5nKQs1MALuBbwHE1MhzLb5gISdq24MuuIY6+ujWep1XNK0VNGHaGtYkHXXGrf3T0RN4k67qVnN3kFXAGDiFL9JXiph918dp4LICFuzd3iDc2N69ry8bJ+h1+cNHLgwCRPDQfiZqsgd4zcCOIaVCJPqbplKI6ZXierYEn2w8HiA8yW7bAXRpsyCeWrUBnRTeO9cp3E0VqLw3fuLhvtU51kS1LhcuEWaNBtKszPTs2I4PkLbFsf6S03ag0fpR8CPyM2OwU3vmCgVTtcbBeQBOMPD8ebAktjUMCnjOZptOKk5DanzTP+nMWDbbeSYZyJTiZtTRuYiXhm+Q7dmDb7RisNYS+MZ1dShljh3zphJtsAFQYsyl2HVipobXJvjqUbfj62yMQzF0orhu2D/F76+v0hqTYJ32WB34p5GKLlzHlDVLEXjdHSQJ36OUdTqVV+q+39NomsqFUojfG1Vlrs+VXx+SEmPn0WYXiK+hTRGrmxAs1UTMiufhakkjpGmxJpL14By5ozmAoh/XjbLlVdQUDSYrQJZviJwk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
